spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_user_management
    username: postgres
    password: kojo2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
